# Site settings
title: Editorial
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/blacksdahistory" # the subpath of your site, e.g. /blog
url: "http://bigboss424.github.io/blacksdahistory" # the base hostname & protocol for your site
author: Aaron Jones
street_address: 3536 McNally Ave
city: Altadena
state: CA
zip_code: 91001
country: United States of America
phone: (559) 761-2046

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/bigboss424
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
